/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static String[] MSGS = {
            "Hello World",
            "I'm rares",
            "and you are watching disney channel."
    };

    public static void main(String[] args) {
        for (String msg : MSGS) {
            System.out.println(msg);
        }
    }
}
