/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAHelloWorld() {
        assertTrue(Arrays.stream(App.MSGS).anyMatch(s -> s.startsWith("Hello World")));
    }

    @Test void appHasAGreeting(){
        String name = "rares";
        assertEquals("I'm " + name, App.greetMsg(name));
    }
}
